import { strict as assert } from "node:assert";
import { GenerationTiming } from "../../src/main/lib/generationTiming.js";
import { buildCodexTokenSnapshot, CodexTurnUsage } from "../../src/main/providers/codex-sdk/codexTokenUsage.js";
import { buildPiTokenSnapshot } from "../../src/main/providers/pi-sdk/piTokenUsage.js";
import { normalizeClaudeTokenUsage } from "../../src/main/providers/claude-sdk/claudeTokenUsage.js";
import { genMsForTurn, sessionSpeed, sessionCacheRate, turnCacheRate } from "../../src/renderer/lib/sessionMetrics.js";
import type { TurnUsageRecord } from "@contracts/runtime";
const timing = new GenerationTiming(0);
timing.delta(100); timing.delta(300); timing.pause();
timing.delta(60_000); timing.delta(60_400); timing.pause();
assert.deepEqual(timing.finish(), { generationMs:600, firstTokenMs:100 });
timing.delta(80_000); assert.equal(timing.finish().generationMs,600,"late deltas cannot change finished timing");
const stalled = new GenerationTiming(0); stalled.delta(10); stalled.delta(110); stalled.delta(5000); stalled.delta(5100);
assert.equal(stalled.finish().generationMs,200,"idle stalls excluded");
const burst = new GenerationTiming(100); burst.delta(200); assert.equal(burst.finish().generationMs,undefined,"single chunk has no fabricated speed");
assert.equal(new GenerationTiming(0).finish().firstTokenMs,undefined,"no output has unknown latency");
const raw={inputTokens:100,cachedInputTokens:80,outputTokens:20,reasoningOutputTokens:5};
const snapshot=buildCodexTokenSnapshot(raw,1000)!;
assert.equal(snapshot.totalProcessedTokens,120,"Codex cached input is included once");
assert.equal(snapshot.cacheReadTokens,80);
assert.equal(snapshot.outputTokens,20,"reasoning is not added twice");
const totals=new CodexTurnUsage(); totals.observe(raw,raw);
const next={...raw,inputTokens:150,cachedInputTokens:100,outputTokens:30};
totals.observe({...raw,inputTokens:50,cachedInputTokens:20,outputTokens:10},next);
totals.observe({...raw,inputTokens:50,cachedInputTokens:20,outputTokens:10},next);
assert.equal(totals.value?.inputTokens,150,"multi-call turn uses thread deltas and ignores duplicates");
assert.equal(buildCodexTokenSnapshot(raw,1000,totals.value)?.totalProcessedTokens,180);
assert.equal(buildCodexTokenSnapshot(raw,1000,totals.value)?.usedTokens,100,"latest request owns occupancy");
const claude=normalizeClaudeTokenUsage({inputTokens:20,cacheReadInputTokens:80,outputTokens:20},{reported:1000})!;
assert.equal(claude.totalProcessedTokens,120,"Anthropic input excludes cache");
assert.equal(claude.cacheReadTokens,80);
const pi=buildPiTokenSnapshot({tokens:100,contextWindow:1000,percent:10},undefined)!;
assert.equal(pi.cacheReadTokens,undefined,"missing SDK counters remain unknown");
const base:TurnUsageRecord={endedAt:1,durationMs:99999,totalProcessedTokens:120,outputTokens:20,cacheReadTokens:80,cacheCreationTokens:0,usedTokens:100,generationMs:1000,firstTokenMs:500};
assert.equal(genMsForTurn([base],undefined,1),1000,"persisted time survives an empty renderer timer");
assert.equal(sessionSpeed([base],[]),20,"reopened history retains speed");
assert.equal(sessionSpeed([base,{...base,endedAt:2,generationMs:undefined}],[]),20,"unmeasured records excluded from both sums");
assert.equal(genMsForTurn([{...base,generationMs:undefined}],[{endedAt:99,genMs:1}],1),null,"time from another turn never mispairs");
assert.equal(turnCacheRate({...base,cacheUsageKnown:false}),null,"unknown cache is not cold zero");
assert.equal(sessionCacheRate([base,{...base,cacheUsageKnown:false,totalProcessedTokens:100000}]),0.8,"unknown cache excluded from averages");
console.log("PASS: generation spans, latency, reload metrics, missing cache and three-provider counter conventions");
